apiVersion: batch/v1
kind: Job
metadata:
  name: auth-db-migration
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migration
          image: ms-auth:latest
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret

          command:
            - /app/efbundle
