apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
data:
  ELASTIC_VERSION: '9.1.0'
  ELASTIC_HOST: 'http://elasticsearch:9200'
  ELASTIC_HOST_WITH_NAMESPACE: 'http://elasticsearch.observability.svc.cluster.local:9200'
