apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret
type: Opaque
stringData:
  ELASTIC_VERSION: '9.1.0'
  ELASTIC_USERNAME: 'elastic'
  ELASTIC_PASSWORD: 'your-secure-password'
  ELASTIC_HOST: 'http://elasticsearch:9200'
  KIBANA_ELASTIC_PASSWORD: 'St8FtiRFXmmXSDcnhvXi'
  KIBANA_ELASTIC_USERNAME: 'kibana_system'
